#!/usr/bin/env ruby

require "superbolide"
require "superbolide/worker"
require "optparse"

OptionParser.new do |opts|
  opts.banner = "Usage: superbolide [options]"

  opts.on("-q", "--queue QUEUE", String, "Specify which queue to use. Default #{Superbolide.config.queue.inspect}") do |q|
    Superbolide.configure{ |config| config.queue = q }
  end

  opts.on("-c", "--concurrency N", Integer, "Specify level of concurrency. Default #{Superbolide.config.concurrency.inspect}") do |c|
    Superbolide.configure do |config|
      config.concurrency = c
      config.pool_size = c + 5
    end
  end

  opts.on("-r", "--require FILE", String, "Require file") do |r|
    require r
  end
end.parse!

if Superbolide.config.api_token == ""
  puts "SUPERBOLIDE_API_TOKEN is not set, exiting"
  exit 1
end

Signal.trap("TERM") do
  Superbolide::Worker.stop()
end

Signal.trap("INT") do
  Superbolide::Worker.stop()
end

Superbolide::Worker.start